Document: hesailidarsdk
Title: Debian hesailidarsdk Manual
Author: <insert document author here>
Abstract: This manual describes what hesailidarsdk is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/hesailidarsdk/hesailidarsdk.sgml.gz

Format: postscript
Files: /usr/share/doc/hesailidarsdk/hesailidarsdk.ps.gz

Format: text
Files: /usr/share/doc/hesailidarsdk/hesailidarsdk.text.gz

Format: HTML
Index: /usr/share/doc/hesailidarsdk/html/index.html
Files: /usr/share/doc/hesailidarsdk/html/*.html
